"""LibriMix dataset access — the project's standard separation benchmark.

Two entry points, both yielding the same :class:`MixtureItem`:

* :meth:`LibriMixDataset.from_metadata` — builds mixtures on the fly from the
  official LibriMix metadata CSVs plus a local LibriSpeech tree. Nothing is
  written to disk and the result is bit-exact reproducible, because the CSV
  pins the source files and their gains.
* :meth:`LibriMixDataset.from_wav_dir` — reads a LibriMix tree already
  generated by the official ``generate_librimix.sh`` script.

Metadata columns follow LibriMix (Cosentino et al. 2020): ``mixture_ID``,
``source_<i>_path``, ``source_<i>_gain``, optionally ``noise_path`` /
``noise_gain``. Sources are scaled by their gain, resampled, length-aligned
(``min`` truncates to the shortest, ``max`` zero-pads to the longest) and summed.
"""
from __future__ import annotations

import csv
import logging
import re
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import soundfile as sf
from scipy.signal import resample_poly

logger = logging.getLogger(__name__)

LIBRISPEECH_SR = 16_000

_SOURCE_PATH_RE = re.compile(r"^source_(\d+)_path$")


@dataclass
class MixtureItem:
    """One benchmark mixture and its reference sources."""

    mixture_id: str
    mixture: np.ndarray            # (n_samples,)
    sources: list[np.ndarray]      # n_sources x (n_samples,)
    sr: int

    @property
    def n_sources(self) -> int:
        return len(self.sources)


def _source_columns(fieldnames: list[str]) -> list[int]:
    """Indices of the ``source_<i>_path`` columns, in ascending order."""
    indices = [
        int(m.group(1))
        for name in fieldnames
        if (m := _SOURCE_PATH_RE.match(name))
    ]
    if not indices:
        raise ValueError(
            "No 'source_<i>_path' column found — this does not look like a "
            f"LibriMix metadata CSV (columns: {fieldnames})."
        )
    return sorted(indices)


def _resolve(path: str, root: Path | None) -> Path:
    """Resolve a metadata source path against the local LibriSpeech tree.

    Metadata ships paths relative to the LibriSpeech root, but a locally
    regenerated CSV may carry absolute ones — both are accepted.
    """
    candidate = Path(path)
    if candidate.is_file():
        return candidate
    if root is not None:
        relative = root / path
        if relative.is_file():
            return relative
        # A CSV generated elsewhere may carry a longer prefix (…/LibriSpeech/train-clean-100/…);
        # retry from the first path component that exists under the given root.
        parts = candidate.parts
        for i in range(len(parts)):
            retry = root.joinpath(*parts[i:])
            if retry.is_file():
                return retry
    raise FileNotFoundError(
        f"Source file not found: {path!r} (LibriSpeech root: {root}). "
        "Pass --librispeech-root pointing at the directory that contains the "
        "subset folders (e.g. the one holding 'train-clean-100')."
    )


def _read_audio(path: Path, target_sr: int) -> np.ndarray:
    audio, sr = sf.read(str(path), dtype="float32", always_2d=False)
    if audio.ndim > 1:
        audio = audio.mean(axis=1)
    if sr != target_sr:
        audio = _resample(audio, sr, target_sr)
    return audio.astype(np.float32, copy=False)


def _resample(audio: np.ndarray, sr_in: int, sr_out: int) -> np.ndarray:
    """Polyphase resampling, matching the official LibriMix generator."""
    if sr_in == sr_out:
        return audio
    gcd = np.gcd(sr_in, sr_out)
    return resample_poly(audio, sr_out // gcd, sr_in // gcd).astype(np.float32)


def fit_lengths(sources: list[np.ndarray], mode: str) -> list[np.ndarray]:
    """Align source lengths: ``min`` truncates, ``max`` zero-pads."""
    if mode not in ("min", "max"):
        raise ValueError(f"mode must be 'min' or 'max', got {mode!r}")
    lengths = [len(s) for s in sources]
    target = min(lengths) if mode == "min" else max(lengths)
    if mode == "min":
        return [s[:target] for s in sources]
    return [np.pad(s, (0, target - len(s))) for s in sources]


class LibriMixDataset:
    """Iterable of :class:`MixtureItem`, lazily decoded.

    Held in an iterable rather than materialised in memory: a LibriMix split is
    tens of hours of audio and the evaluation harness only needs one mixture at
    a time.
    """

    def __init__(self, items: list, loader: Callable[[Any], MixtureItem],
                 sr: int, name: str) -> None:
        self._items  = items
        self._loader = loader
        self.sr      = sr
        self.name    = name

    def __len__(self) -> int:
        return len(self._items)

    def __iter__(self):
        for item in self._items:
            yield self._loader(item)

    @classmethod
    def from_metadata(
        cls,
        metadata_csv: str | Path,
        librispeech_root: str | Path | None = None,
        sr: int = LIBRISPEECH_SR,
        mode: str = "min",
        limit: int | None = None,
    ) -> "LibriMixDataset":
        """Build mixtures on the fly from an official LibriMix metadata CSV.

        Args:
            metadata_csv:     e.g. ``metadata/Libri2Mix/libri2mix_test.csv``
            librispeech_root: directory containing the LibriSpeech subsets
            sr:               target sample rate (16000 or 8000)
            mode:             ``min`` (standard for reporting) or ``max``
            limit:            keep only the first N rows — for smoke runs
        """
        metadata_csv = Path(metadata_csv)
        root = Path(librispeech_root) if librispeech_root else None

        with metadata_csv.open(newline="") as fh:
            reader = csv.DictReader(fh)
            if reader.fieldnames is None:
                raise ValueError(f"Empty metadata file: {metadata_csv}")
            indices = _source_columns(list(reader.fieldnames))
            rows = list(reader)

        if limit is not None:
            rows = rows[:limit]

        def load(row: dict) -> MixtureItem:
            sources = []
            for i in indices:
                path = _resolve(row[f"source_{i}_path"], root)
                gain = float(row.get(f"source_{i}_gain", 1.0) or 1.0)
                sources.append(_read_audio(path, sr) * gain)
            sources = fit_lengths(sources, mode)
            mixture = np.sum(sources, axis=0, dtype=np.float32)
            return MixtureItem(
                mixture_id=row.get("mixture_ID", "?"),
                mixture=mixture,
                sources=sources,
                sr=sr,
            )

        logger.info(
            "LibriMix from metadata: %s — %d mixtures, %d sources, %d Hz, mode=%s",
            metadata_csv.name, len(rows), len(indices), sr, mode,
        )
        return cls(rows, load, sr, name=f"{metadata_csv.stem}/{mode}/{sr}")

    @classmethod
    def from_wav_dir(
        cls,
        root: str | Path,
        mix_dir: str = "mix_clean",
        sr: int = LIBRISPEECH_SR,
        limit: int | None = None,
    ) -> "LibriMixDataset":
        """Read a pre-generated LibriMix split directory.

        Expects the official layout: ``<root>/<mix_dir>/*.wav`` alongside
        source directories ``<root>/s1``, ``<root>/s2``, …
        """
        root = Path(root)
        mix_path = root / mix_dir
        if not mix_path.is_dir():
            raise FileNotFoundError(f"Mixture directory not found: {mix_path}")

        source_dirs = sorted(
            (d for d in root.iterdir() if d.is_dir() and re.fullmatch(r"s\d+", d.name)),
            key=lambda d: int(d.name[1:]),
        )
        if not source_dirs:
            raise FileNotFoundError(f"No source directories (s1, s2, …) under {root}")

        mixtures = sorted(mix_path.glob("*.wav"))
        if limit is not None:
            mixtures = mixtures[:limit]

        def load(path: Path) -> MixtureItem:
            sources = [_read_audio(d / path.name, sr) for d in source_dirs]
            return MixtureItem(
                mixture_id=path.stem,
                mixture=_read_audio(path, sr),
                sources=sources,
                sr=sr,
            )

        logger.info(
            "LibriMix from wav dir: %s — %d mixtures, %d sources",
            root, len(mixtures), len(source_dirs),
        )
        return cls(mixtures, load, sr, name=f"{root.name}/{mix_dir}")
